INSERT INTO `huawai_category` VALUES('1','1','content','1','0','0','0','1','1,2,3,5,162','网站介绍','','','','','about','/html/about/','0','0','array (
  \'ishtml\' => \'1\',
  \'template_list\' => \'default\',
  \'page_template\' => \'page\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'\',
  \'repeatchargedays\' => \'1\',
)','1','0','0','wangzhanjieshao','');
INSERT INTO `huawai_category` VALUES('2','1','content','1','0','1','0,1','0','2','关于我们','','','','about/','aboutus','/html/about/aboutus/','0','0','array (
  \'ishtml\' => \'1\',
  \'template_list\' => \'default\',
  \'page_template\' => \'page\',
  \'meta_title\' => \'关于我们\',
  \'meta_keywords\' => \'关于我们\',
  \'meta_description\' => \'关于我们\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'\',
  \'repeatchargedays\' => \'1\',
)','1','1','0','guanyuwomen','');
INSERT INTO `huawai_category` VALUES('3','1','content','1','0','1','0,1','0','3','联系方式','','','','about/','contactus','/html/about/contactus/','0','0','array (
  \'ishtml\' => \'1\',
  \'template_list\' => \'default\',
  \'page_template\' => \'page\',
  \'meta_title\' => \'联系方式\',
  \'meta_keywords\' => \'联系方式\',
  \'meta_description\' => \'联系方式\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'\',
  \'repeatchargedays\' => \'1\',
)','2','1','0','lianxifangshi','');
INSERT INTO `huawai_category` VALUES('4','1','content','1','0','1','0,1','0','4','版权声明','','','','about/','copyright','http://test.phpcms.cn/index.php?m=content&c=index&a=lists&catid=4','0','0','array (
  \'ishtml\' => \'0\',
  \'template_list\' => \'default\',
  \'page_template\' => \'page\',
  \'meta_title\' => \'版权声明\',
  \'meta_keywords\' => \'版权声明\',
  \'meta_description\' => \'版权声明\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'\',
  \'repeatchargedays\' => \'1\',
)','3','1','0','banquanshengming','');
INSERT INTO `huawai_category` VALUES('5','1','content','1','0','1','0,1','0','5','招聘信息','','','','about/','hr','/html/about/hr/','0','0','array (
  \'ishtml\' => \'1\',
  \'template_list\' => \'default\',
  \'page_template\' => \'page\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'\',
  \'repeatchargedays\' => \'1\',
)','4','1','0','zhaopinxinxi','');
